"""Migration: repositioned 'Corporate Survival Tactics' variants model.

Reads the legacy quotes.json (92 parent laws/principles across 3 books) and
writes the new flat variant-items sequence (~276 items). Each parent expands
into TACTIC / MISTAKE / SCENARIO, each carrying its own corporate-framed
tease + divisive comment_q + reframed body. Parent book/title/author/headline
are retained for the affiliate funnel + stable series label.

Voice: blunt tactical senior colleague. Concrete work scenarios only.
Banned: wisdom, ancient, wait for it, any deferral phrase.

Run:  .\\.venv\\Scripts\\python.exe scripts\\build_corporate_variants.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "quotes.json"

# Per-parent authored copy, keyed by the legacy `title`. Each variant is
# (tease, comment_q, body). tease: payoff/threat first, <=11 words, 1 emoji,
# no deferral. comment_q: divisive binary, ends with the finger emoji.
V: dict[str, dict[str, tuple[str, str, str]]] = {
    # ─────────────────────────── THE 48 LAWS OF POWER ───────────────────────────
    "Introduction": {
        "tactic": ("Office politics is a game — here's the playbook 🎯",
                   "Office politics: play it or pretend it doesn't exist? 👇",
                   "Every workplace runs on power, not the org chart. Learn the moves or get moved."),
        "mistake": ("Pretending you're 'above politics' is why you're stuck ⚠️",
                    "Is 'I just do good work' career advice or career suicide? 👇",
                    "The people who say politics is beneath them are the ones it happens to."),
        "scenario": ("Two equal performers. One gets promoted. Here's why 🎯",
                     "Same output, different outcome — luck or strategy? 👇",
                     "Same results, same hours. One read the room, one didn't. Guess who's the manager now."),
    },
    "Law 1": {
        "tactic": ("Make your boss look brilliant in every meeting 🤝",
                   "Outshine your manager publicly: bold move or career-ender? 👇",
                   "Sharpen your boss's idea, don't replace it. Hand them the spotlight; they hand you the promotion."),
        "mistake": ("Correcting your boss in public is quiet career suicide ⚠️",
                    "Would you fix your boss's mistake in front of the team? 👇",
                    "You won the argument and lost the relationship. Being right in public costs you the next opening."),
        "scenario": ("Your idea, your boss's meeting — who gets the credit? 🎯",
                     "Boss presents your work as theirs — speak up or bank it? 👇",
                     "Let them present it as theirs once. The chip you bank cashes bigger than the callout ever would."),
    },
    "Law 2": {
        "tactic": ("Your loudest critic is your most useful ally ⚔️",
                   "Hire the person who challenged you publicly — yes or no? 👇",
                   "The coworker who fought you has something to prove. Put them on your project; they'll outwork your friends."),
        "mistake": ("Trusting your work-friend with everything will burn you ⚠️",
                    "Real friends at work — asset or liability? 👇",
                    "The friend who knows your salary, your plans, your doubts is the leak you never see coming."),
        "scenario": ("You vented to a work-friend. It reached your boss 🎯",
                     "Vent about your manager to a coworker: ever safe? 👇",
                     "One honest lunch, one repeated line, one cooled relationship with your boss. The friend felt 'safe.'"),
    },
    "Law 3": {
        "tactic": ("Job-hunt in silence, leave from strength 🤐",
                   "Tell your manager you're interviewing — honest or naive? 👇",
                   "Don't announce you're looking. Build quietly, line up the offer, then negotiate from leverage, not hope."),
        "mistake": ("Announcing your plans hands rivals the counter-move ⚠️",
                    "Share your roadmap early or guard it till it's real? 👇",
                    "You floated the idea in standup. By the time you built it, someone with more clout 'owned' it."),
        "scenario": ("They asked your five-year plan. The safe answer 🎯",
                     "Skip-level asks your ambitions — full honesty or filter? 👇",
                     "'Where do you see yourself?' Reveal too much and you're a threat. Reveal too little and you're coasting. Aim narrow."),
    },
    "Law 4": {
        "tactic": ("Stop over-explaining in meetings — it reads as weakness 🤐",
                   "Loud in meetings or silent operator — who gets promoted? 👇",
                   "Say less than you want to. The person who explains the most in the room controls it the least."),
        "mistake": ("The 'just to clarify…' habit is killing your authority ⚠️",
                    "Does over-clarifying make you look careful or junior? 👇",
                    "Every hedging preamble shrinks you. 'Just to clarify, I might be wrong, but—' tells them not to weigh it."),
        "scenario": ("Your boss asks a loaded question. The 3-word answer that wins 🎯",
                     "Loaded question from leadership — full answer or tight one? 👇",
                     "They asked to watch you scramble. You gave one clean sentence and stopped. Silence put the pressure back on them."),
    },
    "Law 5": {
        "tactic": ("Your reputation arrives before you do — engineer it 💼",
                   "Reputation at work: built on results or visibility? 👇",
                   "Decide the two words you want said when you leave the room, then make every interaction prove them."),
        "mistake": ("One missed deadline you didn't flag rewrites your whole rep ⚠️",
                    "One slip-up — does it erase a year of good work? 👇",
                    "Reputation isn't your average; it's your worst unmanaged moment. Silence on a slip is what sticks."),
        "scenario": ("New manager asks around about you. What they hear decides everything 🎯",
                     "Should your rep precede you, or earn it fresh each time? 👇",
                     "Before the new director met you, three people described you in a sentence. That sentence set your ceiling."),
    },
    "Law 6": {
        "tactic": ("Be impossible to ignore in the rooms that decide 📣",
                   "Visible self-promotion: necessary or cringe? 👇",
                   "Quiet competence gets managed; visible competence gets promoted. Put your work where decision-makers actually look."),
        "mistake": ("Doing great work nobody sees is a losing strategy ⚠️",
                    "'My work speaks for itself' — true or career myth? 👇",
                    "Work doesn't speak. People speak about work they noticed. Unseen excellence is just unpaid effort."),
        "scenario": ("Two analysts, same output. One sends the Friday recap 🎯",
                     "Weekly self-update to leadership: smart or try-hard? 👇",
                     "She sent a three-line Friday summary up the chain. He didn't. Leadership only knew one of them existed."),
    },
    "Law 7": {
        "tactic": ("Leave at 6 and still get the credit 🏆",
                   "Delegate the grunt work or grind it yourself for cred? 👇",
                   "Own the strategy and the visible result. Hand off the boring execution. Your name goes on the outcome."),
        "mistake": ("Doing it all yourself is how you stay invisible ⚠️",
                    "Hero-mode solo work: dedication or self-sabotage? 👇",
                    "You did everything so no one could fault you. No one could credit you either. Martyrs don't get promoted."),
        "scenario": ("You did the work. Your teammate presented it. Now what 🎯",
                     "Someone took credit for your work — confront or log it? 👇",
                     "He presented your analysis as his. You didn't explode — you cc'd the proof to the right inbox, calmly."),
    },
    "Law 8": {
        "tactic": ("Make them come to you — control the terms 🪝",
                   "Chase the opportunity or make it chase you? 👇",
                   "Don't beg for the project. Make your work the obvious answer so they bring it to you on your terms."),
        "mistake": ("Always being available makes you the default, not the prize ⚠️",
                    "Instant replies: reliable or easily taken for granted? 👇",
                    "Reply to everything in seconds and you become the help desk, not the hire they fight to keep."),
        "scenario": ("You stopped volunteering for everything. They noticed 🎯",
                     "Stop raising your hand for scraps — power move or risk? 👇",
                     "You quit grabbing every thankless task. Within a month they were asking you to take the ones that mattered."),
    },
    "Law 9": {
        "tactic": ("Win with the result, not the argument 🎯",
                   "Debate it in the meeting or just ship the proof? 👇",
                   "Don't out-argue them. Ship the working version and let the outcome end the debate for you."),
        "mistake": ("Winning the meeting argument can lose you the room ⚠️",
                    "Be right loudly or be right quietly — which wins long-term? 👇",
                    "You dismantled their logic in front of everyone. They remembered the humiliation, not your point."),
        "scenario": ("They doubted your approach. You shipped it anyway 🎯",
                     "Prove skeptics wrong with words or with a demo? 👇",
                     "Instead of defending the plan for a week, you built the prototype over a weekend. The demo ended the argument."),
    },
    "Law 10": {
        "tactic": ("Distance yourself from the team's chronic complainer 🚪",
                   "Is the office cynic dragging your reputation down too? 👇",
                   "Negativity is contagious and it's attributed by association. Be warm, be brief, be elsewhere."),
        "mistake": ("Befriending the office martyr ties you to their ceiling ⚠️",
                    "Guilty by association with the team pessimist — real or not? 👇",
                    "You're kind to the person everyone avoids. Leadership stopped separating their reputation from yours."),
        "scenario": ("The team's 'victim' wants you as their venting partner 🎯",
                     "Comfort the chronic complainer or protect your energy? 👇",
                     "Every coffee became their grievance hour. Your output dipped, your mood dipped, and people noticed the pairing."),
    },
    "Law 11": {
        "tactic": ("Become the one person the project can't run without 🔑",
                   "Be indispensable or be easily replaced — your call? 👇",
                   "Own a piece of the work only you understand. Security isn't loyalty; it's being load-bearing."),
        "mistake": ("Documenting yourself out of a job is a real risk ⚠️",
                    "Share all your knowledge freely or keep an edge? 👇",
                    "You handed over every process doc, then wondered why you were the 'redundant' one in the reorg."),
        "scenario": ("Layoffs hit. The team kept the person who knew the system 🎯",
                     "In a cut, does irreplaceable beat well-liked? 👇",
                     "Two roles, one budget. They kept the one whose departure would break three things by Monday."),
    },
    "Law 12": {
        "tactic": ("Disarm a rival with one unexpected, genuine assist 🤝",
                   "Help a competitor at work: strategy or weakness? 👇",
                   "A single sincere favor to the right person buys more trust than a year of polite distance."),
        "mistake": ("Pure self-interest with no goodwill leaves you exposed ⚠️",
                    "All-business no-favors at work — efficient or isolating? 👇",
                    "You never helped anyone 'off the clock.' When you needed cover, the room was empty."),
        "scenario": ("You helped the rival team hit their deadline. It paid back 🎯",
                     "Bail out a rival team — naive or long game? 👇",
                     "You lent them your best person for two days. Next quarter their lead championed your promotion."),
    },
    "Law 13": {
        "tactic": ("Asking for help? Lead with what's in it for them 🎯",
                   "Appeal to a colleague's interest or their kindness? 👇",
                   "Don't ask for mercy. Frame the ask as their win and the yes becomes easy."),
        "mistake": ("'As a favor to me' is the weakest ask at work ⚠️",
                    "Does guilt-based asking ever actually work in an office? 👇",
                    "You reminded them how much you'd done for them. They heard a debt, not a reason, and stalled."),
        "scenario": ("You needed their team's help. You framed it as their metric 🎯",
                     "Pitch a cross-team ask as your need or their gain? 👇",
                     "Instead of 'please, I'm drowning,' you showed how it hit their numbers too. Approved same day."),
    },
    "Law 14": {
        "tactic": ("Learn what your stakeholders actually want — quietly 🕵️",
                   "Read the room covertly or ask directly every time? 👇",
                   "In every 1:1 and hallway chat, gather what people really care about. Information is positioning."),
        "mistake": ("Oversharing your read of people gets back to them ⚠️",
                    "Tell a coworker you've 'figured them out' — bold or dumb? 👇",
                    "You bragged that you could read the VP. It traveled. Now the VP reads you as a threat."),
        "scenario": ("You learned the real decision-maker wasn't the title 🎯",
                     "Pitch the loudest exec or the silent gatekeeper first? 👇",
                     "The org chart said the director decided. The quiet chief of staff actually did. You briefed them first."),
    },
    "Law 15": {
        "tactic": ("If you take on a workplace rival, don't leave them wounded ⚔️",
                   "Half-win a work conflict or end it cleanly? 👇",
                   "A half-beaten rival becomes a permanent enemy. Resolve it fully or don't start it."),
        "mistake": ("Publicly embarrassing a peer creates a lifelong opponent ⚠️",
                    "Crush a workplace rival or always leave them an exit? 👇",
                    "You 'won' the turf fight and humiliated them. They've been quietly working against you ever since."),
        "scenario": ("You let a beaten rival save face. It came back as loyalty 🎯",
                     "Give a defeated colleague a graceful out — soft or smart? 👇",
                     "You could have ended their credibility in that review. You didn't. They've defended you in rooms you're not in."),
    },
    "Law 16": {
        "tactic": ("Strategic absence makes your contribution obvious 🌙",
                   "Take real PTO and go dark — respected or risky? 👇",
                   "Be slightly less available and people feel your weight. Constant presence makes you furniture."),
        "mistake": ("Being always-on trains them to expect you for free ⚠️",
                    "Answer Slack on vacation: dedicated or doormat? 👇",
                    "You replied from the beach 'just this once,' every trip. Now off-hours you isn't a favor — it's the baseline."),
        "scenario": ("You took a real week off. The gaps showed your value 🎯",
                     "Fully unplug on leave or stay 'reachable for emergencies'? 👇",
                     "You went dark for seven days. Three things stalled without you. Your next review wrote itself."),
    },
    "Law 17": {
        "tactic": ("Be a little unpredictable — it keeps power off-balance 🎲",
                   "Always-consistent or occasionally surprising — who's respected? 👇",
                   "Don't be the person whose every move is forecastable. A little unpredictability buys you leverage."),
        "mistake": ("Being 100% predictable makes you 100% easy to manage around ⚠️",
                    "Is being totally reliable secretly making you replaceable? 👇",
                    "They could script your reaction to anything. So they planned around you instead of consulting you."),
        "scenario": ("You changed your usual answer once. The room recalibrated 🎯",
                     "Push back when you always agree — power move or whiplash? 👇",
                     "You'd rubber-stamped every plan for a year. The one time you paused and questioned it, everyone leaned in."),
    },
    "Law 18": {
        "tactic": ("Don't wall yourself off — visibility is protection 🚪",
                   "Heads-down isolation or stay in the mix to survive? 👇",
                   "The person nobody sees is the easiest to cut. Stay in the flow of information and people."),
        "mistake": ("Going heads-down 'to focus' is how you get forgotten ⚠️",
                    "Is deep-work isolation quietly ending your career? 👇",
                    "You skipped the lunches and the syncs to grind. When opportunities got handed out, you weren't in the room."),
        "scenario": ("The remote worker who never showed up got cut first 🎯",
                     "Camera off and silent — efficient or endangered? 👇",
                     "Same performance, two people. The one who stayed visible in channels survived the reorg. The ghost didn't."),
    },
    "Law 19": {
        "tactic": ("Know exactly who you're dealing with before you push 🧭",
                   "Read someone's power before challenging them — always? 👇",
                   "Map the person's allies and ego before you cross them. The wrong target ends careers."),
        "mistake": ("Snapping at the 'quiet' coworker who's wired to leadership ⚠️",
                    "Underestimate a low-title colleague — survivable or fatal? 👇",
                    "You dismissed the junior PM in a meeting. Turns out she has the CEO's ear. That email aged badly."),
        "scenario": ("You checked who someone knew before you opposed them 🎯",
                     "Vet a rival's backers before the fight — paranoid or wise? 👇",
                     "Before pushing back on the proposal, you learned who sponsored it. You reframed instead of attacked. Smart."),
    },
    "Law 20": {
        "tactic": ("Don't pick a side in a team feud — stay the neutral asset 🤝",
                   "Pick a faction in office politics or stay independent? 👇",
                   "Commit to a camp and you inherit its enemies. Stay useful to all sides and you outlast the war."),
        "mistake": ("Loudly joining one manager's camp burns the other bridge ⚠️",
                    "Is being 'loyal to one boss' a trap when they leave? 👇",
                    "You were known as their person. They left. Their replacement cleaned house, starting with the loyalists."),
        "scenario": ("Two directors at war. You stayed useful to both 🎯",
                     "In a leadership turf war, ally or stay Switzerland? 👇",
                     "Everyone picked a side and got bloodied. You stayed neutral and competent. You're the one both still trust."),
    },
    "Law 21": {
        "tactic": ("Let them underestimate you — then deliver 🎭",
                   "Play modest then overdeliver, or signal strength early? 👇",
                   "Sometimes the smartest move is to seem less sharp than you are until it counts."),
        "mistake": ("Showing all your cards in week one sets impossible expectations ⚠️",
                    "Sprint hard on day one or pace the reveal? 👇",
                    "You stunned them in month one. Now that's the baseline, and 'merely excellent' reads as a decline."),
        "scenario": ("They thought you'd miss it. You'd already shipped it 🎯",
                     "Let a doubter underestimate you on purpose — smart? 👇",
                     "He assumed you couldn't handle the integration. You let him. You handed it done while he was still doubting."),
    },
    "Law 22": {
        "tactic": ("When you can't win the fight, convert the surrender into time ⏳",
                   "Concede a battle to win the war — weak or wise? 👇",
                   "Lose the unwinnable argument gracefully, keep your standing, and outlast the decision."),
        "mistake": ("Fighting a reorg you can't stop just marks you as the problem ⚠️",
                    "Resist a doomed decision loudly or adapt fast? 👇",
                    "You waged war on the restructure for weeks. It happened anyway, and now you're 'not a team player.'"),
        "scenario": ("You stopped resisting the new system and quietly mastered it 🎯",
                     "Mandated tool you hate — protest or become the expert? 👇",
                     "Everyone complained about the migration. You learned it cold. Now you run the trainings and own the room."),
    },
    "Law 23": {
        "tactic": ("Pour your energy into the one project that gets you seen 🎯",
                   "Spread across five projects or own one that matters? 👇",
                   "Five half-owned projects make you forgettable. One visible, finished win makes your case."),
        "mistake": ("Saying yes to everything dilutes the work that counts ⚠️",
                    "Is being 'helpful on everything' wrecking your promotion case? 👇",
                    "You touched twenty things and owned none. At review time there was no single thing to point at."),
        "scenario": ("You dropped the busywork and went all-in on one bet 🎯",
                     "Cut your commitments to focus — brave or career risk? 👇",
                     "You renegotiated off three side projects. The one you kept became the line item in your promotion packet."),
    },
    "Law 24": {
        "tactic": ("Master the unwritten rules of how your org actually works 🎩",
                   "Play the corporate game well or refuse on principle? 👇",
                   "Every company has a hidden etiquette. The ones who read it rise; the ones who scoff stall."),
        "mistake": ("Treating 'culture fit' rituals as beneath you costs you ⚠️",
                    "Skip the office norms you find fake — integrity or error? 👇",
                    "You skipped the offsite, the lunches, the small talk. Skills intact, sponsorship gone."),
        "scenario": ("You learned how decisions really get made here 🎯",
                     "Formal process or the real backchannel — which do you work? 👇",
                     "The approval 'process' was theater. Real calls happened in a Thursday huddle. You got yourself into it."),
    },
    "Law 25": {
        "tactic": ("Reintroduce yourself — upgrade the role people see you in 🦋",
                   "Can you escape the 'junior' label at your own company? 👇",
                   "People freeze you at the version they met. Deliberately show a bigger one until it sticks."),
        "mistake": ("Letting your first-year reputation define year four ⚠️",
                    "Is your old reputation at this company holding you hostage? 👇",
                    "You grew a lot. They still treat you like the nervous new hire because you never reset the image."),
        "scenario": ("You changed how you showed up. The room re-rated you 🎯",
                     "Rebrand yourself internally or just job-hop to reset? 👇",
                     "New posture, sharper updates, fewer hedges. Within a quarter, leadership stopped talking past you."),
    },
    "Law 26": {
        "tactic": ("Stay out of the blast radius — keep your hands clean 🧼",
                   "Distance from a doomed project early — loyal or smart? 👇",
                   "When something's going to fail, don't be the visible name on it. Proximity is blame."),
        "mistake": ("Defending a sinking project to look loyal sinks you with it ⚠️",
                    "Go down with the failing project or step back early? 👇",
                    "You championed it to the end out of loyalty. It failed. Now you're the face of the failure."),
        "scenario": ("The project imploded. You'd documented your warnings 🎯",
                     "Paper-trail your concerns or trust verbal alignment? 👇",
                     "When it collapsed, the post-mortem hunted for blame. Your written, dated concerns kept your name clear."),
    },
    "Law 27": {
        "tactic": ("Give people a mission to rally around and you lead it 🔥",
                   "Inspire a team with a story or just assign the tasks? 👇",
                   "People follow meaning, not tickets. Frame the work as something worth believing and you're the leader."),
        "mistake": ("Leading with process and no story loses the room ⚠️",
                    "Does 'just hit the deadline' actually motivate anyone? 👇",
                    "You managed the plan perfectly and inspired no one. The team did the minimum and you wondered why."),
        "scenario": ("You named the mission. The team started self-organizing 🎯",
                     "Sell the why or just push the what — what moves people? 👇",
                     "You stopped listing tasks and named the outcome that mattered. People started bringing ideas unasked."),
    },
    "Law 28": {
        "tactic": ("Pitch with total conviction — hesitation kills good ideas 💥",
                   "Bold half-ready pitch or polished but timid — which wins? 👇",
                   "A confident ask beats a perfect one delivered apologetically. Commit in the room or don't go in."),
        "mistake": ("Hedging your proposal invites everyone to poke holes ⚠️",
                    "Does 'this might be dumb but…' ever land well? 👇",
                    "You opened with three disclaimers. They spent the meeting on your doubts instead of your idea."),
        "scenario": ("You walked in certain. They approved it on the spot 🎯",
                     "Ask for the budget boldly or build a careful case? 👇",
                     "Same numbers, different delivery. You stated it as the obvious move, not a request. They said yes."),
    },
    "Law 29": {
        "tactic": ("Plan to the end — including who reacts and how 🧩",
                   "Plan three moves ahead or adapt as it unfolds? 👇",
                   "Map the whole sequence before you start: approvals, pushback, who'll feel threatened. Surprises are unplanned failures."),
        "mistake": ("Launching without thinking past step one detonates later ⚠️",
                    "Is 'we'll figure it out' leadership or a time bomb? 👇",
                    "You shipped phase one with no plan for the politics of phase two. Phase two is where it died."),
        "scenario": ("You'd already mapped the objections before the meeting 🎯",
                     "Pre-game the objections or handle them live? 👇",
                     "Every pushback they raised, you'd pre-answered in the deck. The decision took ten minutes."),
    },
    "Law 30": {
        "tactic": ("Make the hard win look effortless — hide the grind 🪶",
                   "Show the long hours or make it look easy — which earns more? 👇",
                   "Broadcasting how hard it was reads as struggling. Deliver clean and let it look natural."),
        "mistake": ("Performing your exhaustion makes you look barely capable ⚠️",
                    "Does 'I was up till 2am on this' impress or worry leadership? 👇",
                    "You wanted credit for the effort. They heard 'this person is underwater' and scoped down your role."),
        "scenario": ("You delivered big and said it was 'no problem' 🎯",
                     "Downplay the effort or claim every hour of it? 👇",
                     "It nearly broke you. You shipped it and shrugged. They started handing you the high-stakes work."),
    },
    "Law 31": {
        "tactic": ("Frame the choice so every option still works for you ♟️",
                   "Give your boss options or one recommendation? 👇",
                   "Don't ask open questions. Offer two paths you've already made sure you win either way."),
        "mistake": ("Asking 'what should we do?' hands away your leverage ⚠️",
                    "Open-ended questions to leadership: humble or weak? 👇",
                    "You asked the VP to decide from scratch. They picked the path that didn't need you."),
        "scenario": ("You presented two options. Both routed through your team 🎯",
                     "Control the menu or let leadership define it? 👇",
                     "You let them feel in charge by choosing — between two outcomes you'd already designed to favor you."),
    },
    "Law 32": {
        "tactic": ("Sell the outcome people wish were true, then deliver toward it ✨",
                   "Pitch the dream or the realistic plan — which gets funded? 👇",
                   "Dry plans don't get budget. Attach the work to the future they already want and watch doors open."),
        "mistake": ("All-spreadsheet, no-vision pitches die in committee ⚠️",
                    "Does pure realism lose to a compelling story in funding? 👇",
                    "Your numbers were airtight and forgettable. The team with the vision and worse math got the headcount."),
        "scenario": ("You painted the after-state. The room funded it 🎯",
                     "Lead a pitch with data or with the vision? 👇",
                     "You opened with the world after the project shipped. By the time you reached the numbers, they were sold."),
    },
    "Law 33": {
        "tactic": ("Find what each stakeholder actually optimizes for 🔍",
                   "Tailor your pitch per exec or one deck for all? 👇",
                   "Everyone has one thing they really protect: budget, risk, ego, time. Aim at it and the yes is fast."),
        "mistake": ("One-size pitching to different stakeholders loses all of them ⚠️",
                    "Same pitch to every exec — efficient or lazy? 👇",
                    "You ran the identical deck past finance and product. Neither felt it was for them. Both passed."),
        "scenario": ("You learned the CFO only cared about risk. You led with it 🎯",
                     "Open with what they fear or what you want? 👇",
                     "She'd killed three proposals on risk. You opened with the risk plan. First one she approved all quarter."),
    },
    "Law 34": {
        "tactic": ("Carry yourself like you're already at the next level 👑",
                   "Act senior before the title or wait to be anointed? 👇",
                   "People treat you at the level you carry. Operate like the role you want before it's yours."),
        "mistake": ("Acting junior 'until it's official' keeps it unofficial ⚠️",
                    "Does waiting for the title to act senior backfire? 👇",
                    "You stayed in your lane waiting for permission. They promoted the person already behaving like the lead."),
        "scenario": ("You started showing up like the manager. They made you one 🎯",
                     "Step into authority early — presumptuous or proof? 👇",
                     "Before the title, you ran the meeting, owned the call, set the standard. The promotion just caught up."),
    },
    "Law 35": {
        "tactic": ("Time the ask — read when leadership can actually say yes ⏱️",
                   "Pitch when it's ready or when they're receptive? 👇",
                   "The same request lands or dies on timing. Read the budget cycle and the mood before you ask."),
        "mistake": ("Great ask, terrible moment — denied on bad timing ⚠️",
                    "Does timing beat merit when asking for a raise? 👇",
                    "You asked for the raise the week after the team missed target. Right case, fatally wrong week."),
        "scenario": ("You waited two weeks for the right moment. Instant yes 🎯",
                     "Strike now or wait for the opening — what wins? 👇",
                     "You sat on the request until the big win landed. Asked Monday after. Approved before lunch."),
    },
    "Law 36": {
        "tactic": ("Ignore the pointless slight — engaging makes it real 🙅",
                   "Clap back at a passive-aggressive coworker or ignore it? 👇",
                   "Reacting to a jab elevates it. Disdain shrinks it. Pick the fights that move your career."),
        "mistake": ("Litigating every small disrespect makes you the drama ⚠️",
                    "Is responding to every slight strength or self-sabotage? 👇",
                    "You replied-all to set the record straight. Now you're 'difficult,' and they're still fine."),
        "scenario": ("You let the snipe go. It died; they looked petty 🎯",
                     "Address a public dig immediately or starve it? 👇",
                     "He took a shot in the meeting. You moved on like it didn't register. The room noted who looked small."),
    },
    "Law 37": {
        "tactic": ("Make your work a visible spectacle, not a buried doc 🎬",
                   "A great demo or a great document — which gets remembered? 👇",
                   "A sharp visible moment beats a perfect file no one opens. Engineer the reveal."),
        "mistake": ("Burying your win in a doc nobody opens wastes it ⚠️",
                    "Does a flawless report beat a memorable demo? 👇",
                    "Your analysis was brilliant and 40 pages deep. The team that made a 2-minute demo got the funding."),
        "scenario": ("You turned the result into a 90-second demo. It traveled 🎯",
                     "Present the win live or send the deck? 👇",
                     "Instead of emailing the report, you ran a tight live demo. People forwarded it. Leadership asked for you."),
    },
    "Law 38": {
        "tactic": ("Think independently — but don't broadcast every contrarian take 🎭",
                   "Voice every disagreement or pick your moments? 👇",
                   "Keep your sharper opinions for where they pay. Constant contrarianism gets you labeled, not heard."),
        "mistake": ("Being the meeting contrarian gets you uninvited ⚠️",
                    "Is the 'devil's advocate' role respected or avoided? 👇",
                    "You challenged everything to seem rigorous. They stopped inviting you to the room where it's decided."),
        "scenario": ("You held the contrarian take for the 1:1, not the room 🎯",
                     "Disagree publicly or privately with leadership? 👇",
                     "You didn't torch the plan in the meeting. You raised it privately with the owner. It changed — quietly, with credit."),
    },
    "Law 39": {
        "tactic": ("Create motion to surface what people really think 🌊",
                   "Stir a stalled decision or wait it out? 👇",
                   "A well-placed question can unstick a frozen team and reveal the real blockers and players."),
        "mistake": ("Stirring chaos you can't steer makes you the blocker ⚠️",
                    "Is shaking things up leadership or just noise? 👇",
                    "You forced the conflict into the open with no plan to land it. Now you own the mess you exposed."),
        "scenario": ("You asked the question everyone avoided. It moved 🎯",
                     "Name the elephant in the meeting or let it sit? 👇",
                     "Three meetings circled it. You said it plainly, calmly, once. The decision finally happened."),
    },
    "Law 40": {
        "tactic": ("Be wary of the 'great opportunity' with no clear payoff 🎯",
                   "Take the high-visibility project with no upside — yes/no? 👇",
                   "Free, urgent, 'great exposure' work often costs the most. Price every yes in time and credit."),
        "mistake": ("Grabbing every 'opportunity' is how you burn out unseen ⚠️",
                    "Is 'great for your growth' usually code for unpaid work? 👇",
                    "You took the stretch project 'for exposure.' It buried you, the credit went up, the raise didn't."),
        "scenario": ("You said no to the glamorous trap. Dodged the bullet 🎯",
                     "Decline a prestigious doomed project — brave or career risk? 👇",
                     "Everyone wanted the flashy initiative. You read the no-resources reality and passed. It cratered without you."),
    },
    "Law 41": {
        "tactic": ("Following a legend? Don't imitate — define your own win 👞",
                   "Take the rockstar's old role: copy them or reinvent it? 👇",
                   "Stepping into a star's seat by copying them guarantees the comparison kills you. Change the game."),
        "mistake": ("Trying to be the beloved predecessor 2.0 sets you up to lose ⚠️",
                    "Is replacing a popular leader a no-win unless you pivot? 👇",
                    "You ran it exactly like they did, hoping for the same love. You just looked like a worse copy."),
        "scenario": ("You redefined the role instead of inheriting it 🎯",
                     "Honor the predecessor's playbook or rewrite it? 👇",
                     "The legend's shoes were a trap. You scoped a different mandate. Now it's your win, not their echo."),
    },
    "Law 42": {
        "tactic": ("In a hostile team, address the instigator, not the noise 🎯",
                   "Manage the loud troublemaker or the whole team's mood? 👇",
                   "One person usually drives the dysfunction. Solve them and the rest of the team resets."),
        "mistake": ("Disciplining the whole team for one person's behavior ⚠️",
                    "Punish the group for one bad actor — fair or fatal? 👇",
                    "You added rules for everyone to avoid confronting one person. The good people felt punished and left."),
        "scenario": ("You handled the source. The team's tension dissolved 🎯",
                     "Confront the ringleader directly or work around them? 👇",
                     "One person seeded every standup with cynicism. You addressed them one-on-one. The mood flipped in a week."),
    },
    "Law 43": {
        "tactic": ("Win cooperation through what they care about, not authority ❤️",
                   "Lead through buy-in or through positional power? 👇",
                   "Orders get compliance; understanding their stakes gets commitment. Work the heart and the mind."),
        "mistake": ("Pulling rank to force a 'yes' breeds quiet sabotage ⚠️",
                    "Does 'because I said so' management ever actually work? 👇",
                    "You mandated it. They complied to your face and slow-walked it everywhere you couldn't see."),
        "scenario": ("You sold the why first. They executed without being pushed 🎯",
                     "Mandate the change or build the case for it? 👇",
                     "Instead of the directive, you showed each person what it solved for them. Adoption happened on its own."),
    },
    "Law 44": {
        "tactic": ("Mirror a difficult colleague's style to defuse them 🪞",
                   "Match a hostile coworker's energy or stay neutral? 👇",
                   "Reflecting someone's own approach back disarms them and reveals their game without you saying a word."),
        "mistake": ("Out-aggressing an aggressive coworker escalates into your problem ⚠️",
                    "Fight fire with fire at work — effective or career-ending? 👇",
                    "You matched their hostility blow for blow. Now there are two problems, and one of them is you."),
        "scenario": ("You calmly mirrored their tactic. They backed down 🎯",
                     "Expose a manipulator by mirroring or by confronting? 👇",
                     "Every time they deflected, you reflected it back evenly. The pattern became obvious to the whole room — not from you."),
    },
    "Law 45": {
        "tactic": ("Push change in small doses people can absorb 🔧",
                   "Big-bang reorg or incremental change — which actually sticks? 👇",
                   "Announce the need for change, then move in increments. Too much at once triggers the immune response."),
        "mistake": ("Ripping up everything on day one gets the new lead rejected ⚠️",
                    "Should a new manager change things fast or earn it first? 👇",
                    "You overhauled the whole process in week two. The team didn't resist the change — they resisted you."),
        "scenario": ("You changed one thing, proved it, then the next 🎯",
                     "Earn trust before reform or reform to prove yourself? 👇",
                     "You shipped one small visible improvement first. The win bought you permission for the big one."),
    },
    "Law 46": {
        "tactic": ("Stay relatable — flawless coworkers attract quiet resentment 🫧",
                   "Is being the 'perfect' employee making you a target? 👇",
                   "A small visible humility or shared struggle buys allies. Untouchable people get undermined."),
        "mistake": ("Performing perfection isolates you from your own team ⚠️",
                    "Does the 'never wrong' colleague get respect or knives? 👇",
                    "You never admitted a miss. The team stopped rooting for you and started waiting for the fall."),
        "scenario": ("You owned a small mistake openly. Trust went up 🎯",
                     "Admit a mistake to your team or protect the image? 👇",
                     "You said 'that call was mine and it was wrong' in standup. The room relaxed. People started leveling with you."),
    },
    "Law 47": {
        "tactic": ("Hit the goal and stop — overreach undoes the win 🛑",
                   "Quit while ahead or push for the bigger swing? 👇",
                   "The win is fragile right after you get it. Consolidate before you chase more."),
        "mistake": ("Pushing for more right after a win often gives it all back ⚠️",
                    "After a big win, press the advantage or lock it in? 👇",
                    "You parlayed the promotion into an immediate bigger ask. The greed read poorly and cost you the goodwill."),
        "scenario": ("You banked the win instead of pressing it. Smart 🎯",
                     "Capitalize on momentum or secure the gain first? 👇",
                     "You'd just landed the lead role. You resisted the urge to renegotiate everything. You looked solid, not greedy."),
    },
    "Law 48": {
        "tactic": ("Stay adaptable — rigid plans break in real orgs 🌊",
                   "Hold the plan or bend with the org — which survives? 👇",
                   "Orgs shift under you. The people who flex with the reorg outlast the ones married to last quarter's plan."),
        "mistake": ("Rigidly defending 'the original plan' marks you as stuck ⚠️",
                    "Is sticking to the plan discipline or denial? 👇",
                    "The market moved, the priorities moved, and you defended the Q1 roadmap into Q3. You moved with it — out."),
        "scenario": ("You dropped the dead plan fast. You looked like a leader 🎯",
                     "Abandon a failing strategy early or see it through? 👇",
                     "When the data turned, you killed your own initiative first and pivoted. Leadership noticed who wasn't precious."),
    },

    # ───────────────────────────── ATOMIC HABITS ─────────────────────────────
    "Atomic Habits": {
        "tactic": ("Your career is built by tiny daily reps, not big swings 🧱",
                   "Career growth: one big move or 100 small ones? 👇",
                   "The promotion is a lagging indicator of a year of small, boring, repeated work habits."),
        "mistake": ("Waiting for the 'big break' is why you're still stuck ⚠️",
                    "Is 'waiting for the right opportunity' a plan or a cope? 👇",
                    "Nobody gets discovered. They get 1% better daily until they're undeniable."),
        "scenario": ("Two hires, year one. One did the boring reps 🎯",
                     "Flashy output or quiet consistency — who lasts? 👇",
                     "Same start. One chased visible wins, one compounded small ones. Year two wasn't close."),
    },
    "Compound Effect": {
        "tactic": ("One sharper email a day compounds into authority 📈",
                   "Does small daily improvement actually beat raw talent? 👇",
                   "Get 1% better at one work skill daily. In a year you're the person they consult."),
        "mistake": ("'It's just one skipped week' is how careers flatline ⚠️",
                    "Is an off-week harmless or the start of the slide? 👇",
                    "The decline isn't a cliff. It's small skipped reps no one notices until your role shrinks."),
        "scenario": ("She spent 20 min/day learning the tool. Year later she owns it 🎯",
                     "20 minutes daily upskilling or weekend cram sessions? 👇",
                     "No course, no bootcamp. Twenty minutes a day on one system. Now the team routes through her."),
    },
    "Systems": {
        "tactic": ("Build a system for visibility, not a goal for it 🔁",
                   "'Get promoted' goal or a weekly system — which works? 👇",
                   "Drop 'get promoted.' Build the weekly habit of shipping and surfacing one visible win. The title follows."),
        "mistake": ("Setting goals with no system is why January dies by March ⚠️",
                    "Are career goals useless without a weekly system? 👇",
                    "You set the goal and nothing changed because you changed nothing you do on Tuesdays."),
        "scenario": ("He stopped setting goals and built a Friday ritual 🎯",
                     "Annual goals or a repeatable weekly ritual? 👇",
                     "Every Friday: one recap up the chain, one skill rep, one relationship touch. Promotion was inevitable."),
    },
    "The Plateau": {
        "tactic": ("Push through the flat stretch — that's where most quit 📉",
                   "The plateau: grind through it or change tactics? 👇",
                   "Results lag effort badly. The months that feel pointless are the ones building the breakthrough."),
        "mistake": ("Quitting at the plateau hands the win to whoever stayed ⚠️",
                    "Is leaving a 'stuck' role wisdom or quitting early? 👇",
                    "You left because nothing was happening. It happens right after — for your replacement."),
        "scenario": ("Six months of nothing. Then everything, at once 🎯",
                     "When progress stalls — pivot or hold the line? 👇",
                     "Two flat quarters. He almost left. Q3 the work compounded visibly and he got the lead role."),
    },
    "Identity": {
        "tactic": ("Act like the operator you want to be seen as — now 🧭",
                   "Become senior by identity or wait for the title? 👇",
                   "Don't 'try to get promoted.' Be the person who already operates at that level. People follow the identity."),
        "mistake": ("'I'm just not a leadership person' is a self-imposed ceiling ⚠️",
                    "Is 'that's not who I am' honesty or a cage? 👇",
                    "You opted out of the stretch because it 'wasn't you.' The story you tell becomes the role you keep."),
        "scenario": ("She started saying 'I own this.' The org agreed 🎯",
                     "Claim ownership early or earn the right first? 👇",
                     "She stopped saying 'I just help with.' Started saying 'I run.' Same work, completely different treatment."),
    },
    "Habit Loop": {
        "tactic": ("Engineer the trigger and the work happens itself 🔁",
                   "Discipline or a good trigger — which actually sustains? 👇",
                   "Don't rely on motivation. Tie the work habit to a cue you can't miss: standup, calendar, login."),
        "mistake": ("Relying on willpower for consistency is why it doesn't last ⚠️",
                    "Is 'just be disciplined' real advice or a setup to fail? 👇",
                    "Willpower runs out by Wednesday. The people who stay consistent built a cue, not grit."),
        "scenario": ("He attached the weekly update to his Friday logout 🎯",
                     "Reminders to self or a habit tied to a cue? 👇",
                     "Update never got skipped again — because it fired automatically when he closed the laptop Friday."),
    },
    "1st Law": {
        "tactic": ("Make your good work impossible for leadership to miss 👀",
                   "Should good work be visible by design or speak for itself? 👇",
                   "Put the win where decision-makers already look — the channel, the recap, the demo. Obvious beats hidden."),
        "mistake": ("Hoping someone notices your work is not a strategy ⚠️",
                    "Does quietly waiting to be noticed ever pay off? 👇",
                    "You assumed the work was obvious. It was obvious only to you, and you don't sign off your raise."),
        "scenario": ("She made one change: the work became visible 🎯",
                     "Engineer visibility or trust the org to spot you? 👇",
                     "Same output, one new habit — a public Friday recap. In a quarter, leadership knew her name."),
    },
    "Scorecard": {
        "tactic": ("Track where your work hours actually go for one week 🧾",
                   "Audit your own time or just feel busy? 👇",
                   "Log it honestly for a week. The gap between 'busy' and 'building career capital' is the whole game."),
        "mistake": ("'I'm slammed' with nothing to show is the trap ⚠️",
                    "Is being constantly busy a flex or a red flag? 👇",
                    "You were drowning in tasks and had zero promotable wins. Busy isn't the same as building."),
        "scenario": ("He audited his week. 60% was invisible glue work 🎯",
                     "Is invisible 'glue work' noble or career-limiting? 👇",
                     "The log was brutal: most of his week held the team together and none of it showed in review."),
    },
    "Intentions": {
        "tactic": ("Name the exact when-and-where or the work won't happen 🗓️",
                   "Vague 'I'll get to it' or a scheduled slot — which delivers? 👇",
                   "'I'll prep the deck' fails. 'I'll prep the deck 9am Tuesday before standup' ships."),
        "mistake": ("'When I get time' is the phrase that kills your best work ⚠️",
                    "Does 'I'll do it when I have bandwidth' ever happen? 👇",
                    "The strategic work never had a slot, so the urgent work ate it. Every single week."),
        "scenario": ("She blocked 8–9am for the work that gets her promoted 🎯",
                     "Protect a daily focus block or stay reactive? 👇",
                     "One recurring hold for career-building work, defended ruthlessly. That hour built the case the reviews rewarded."),
    },
    "Habit Stacking": {
        "tactic": ("Bolt the new habit onto one you already never skip 🔗",
                   "Build habits from scratch or stack onto existing ones? 👇",
                   "'After I post standup, I send one relationship message.' Anchor it to a thing you already do daily."),
        "mistake": ("Trying to add an isolated new habit is why it doesn't stick ⚠️",
                    "Is a standalone new routine doomed without an anchor? 👇",
                    "The new habit floated with nothing to attach to, so it quietly disappeared by week two."),
        "scenario": ("He stacked 'one learning note' onto his lunch 🎯",
                     "Anchor learning to a daily ritual or wing it? 👇",
                     "After lunch, one note on something he learned. A year of notes became the internal doc everyone uses."),
    },
    "Environment": {
        "tactic": ("Redesign your workspace so the right work is the default 🪟",
                   "Does your setup pull you toward deep work or Slack? 👇",
                   "Notifications off, focus doc open, phone in a drawer. Make the productive choice the path of least resistance."),
        "mistake": ("Blaming your focus when your environment is the problem ⚠️",
                    "Is poor focus a discipline issue or an environment one? 👇",
                    "You fought distraction with willpower while sitting in a notification firehose. The setup won."),
        "scenario": ("She moved Slack off her first screen. Output doubled 🎯",
                     "Default-open Slack or default-open the work? 👇",
                     "One change: the deep-work doc opened on login, not the inbox. The first hour stopped vanishing."),
    },
    "2nd Law": {
        "tactic": ("Make the career-building work attractive, not a chore ✨",
                   "Force yourself to upskill or make it genuinely appealing? 👇",
                   "Pair the boring rep with something you want — the good coffee, the good playlist. Make it pull you."),
        "mistake": ("Treating growth work as punishment guarantees you skip it ⚠️",
                    "Does 'grind even if you hate it' actually last? 👇",
                    "You framed learning as a sacrifice. Anything framed as punishment gets avoided. Every time."),
        "scenario": ("He only did the hard skill work at the good café 🎯",
                     "Bundle a treat with the hard work or pure discipline? 👇",
                     "Saturday skill-building only happened with the café and the playlist attached. So it actually happened."),
    },
    "Temptation Bundling": {
        "tactic": ("Pair the dull career task with something you crave 🎧",
                   "Bundle a reward with grunt work or just push through? 👇",
                   "Only let yourself have the thing you want while doing the thing you avoid. The avoidance ends."),
        "mistake": ("Pure willpower on tedious work is the slowest path ⚠️",
                    "Is white-knuckling boring tasks discipline or inefficiency? 👇",
                    "You grinded the tedious reporting on raw discipline and dreaded it daily. Bundling would've ended that in a week."),
        "scenario": ("She only listened to her favorite podcast doing expenses 🎯",
                     "Reward-bundle the task you hate or just suffer it? 👇",
                     "The task she'd dodged for months got done weekly — because it was the only time she let herself listen."),
    },
    "Culture": {
        "tactic": ("Get into the room where your habits are the norm 👥",
                   "Do ambitious peers raise you or just intimidate? 👇",
                   "Find the team or circle where the behavior you want is already standard. You'll rise to the room."),
        "mistake": ("Staying on a coasting team makes coasting feel normal ⚠️",
                    "Does your team's average quietly become your ceiling? 👇",
                    "You matched the room. The room was comfortable and unambitious. So now, so are you."),
        "scenario": ("He moved to the team that shipped relentlessly 🎯",
                     "Switch to a more driven team or fix your current one? 👇",
                     "Same person, new team where high output was the baseline. Within months his standard quietly reset upward."),
    },
    "Reframe": {
        "tactic": ("'I get to own this' beats 'I have to do this' 🔁",
                   "Is reframing real leverage or just positive-thinking fluff? 👇",
                   "The stretch assignment is a burden or an audition depending only on the sentence you tell yourself."),
        "mistake": ("Narrating everything as a burden makes you the burnt-out one ⚠️",
                    "Does constant 'ugh, I have to' talk cost you opportunities? 👇",
                    "You called every project a grind out loud. Leadership stopped handing the good ones to the person who dreads work."),
        "scenario": ("She started calling hard projects 'reps.' It changed her rep 🎯",
                     "Does how you talk about work change how you're seen? 👇",
                     "Same workload, new framing — 'good rep' not 'ugh.' People started seeing someone built for more."),
    },
    "3rd Law": {
        "tactic": ("Make the first step of the work stupidly easy 🪜",
                   "Lower the barrier or push harder through resistance? 👇",
                   "Open the doc the night before. Pre-load step one so starting tomorrow takes zero willpower."),
        "mistake": ("Big intimidating first steps are why you procrastinate ⚠️",
                    "Is procrastination laziness or a too-big first step? 👇",
                    "You didn't avoid the report. You avoided the blank page. Shrink the start and the avoidance dies."),
        "scenario": ("He left the deck open on slide one overnight 🎯",
                     "Pre-stage tomorrow's work or rely on morning willpower? 👇",
                     "Every night he set up the one easy first action. Mornings stopped being a fight to begin."),
    },
    "Motion vs Action": {
        "tactic": ("Ship the rough version — motion isn't progress 🚶",
                   "Endless prep or an ugly first ship — which moves you? 👇",
                   "Researching, planning, organizing feels productive and isn't. One shipped draft beats a week of motion."),
        "mistake": ("'Getting ready to start' is the most comfortable way to fail ⚠️",
                    "Is over-preparing diligence or fear in disguise? 👇",
                    "You optimized your notes, your tools, your plan — for weeks. The person who shipped ugly got the credit."),
        "scenario": ("She shipped the messy v1 while he still 'prepared' 🎯",
                     "Polish before showing or show then iterate? 👇",
                     "He had the better plan and nothing to show. She had a rough demo and the room's attention."),
    },
    "Two-Minute Rule": {
        "tactic": ("Shrink the habit until it's too small to skip ⏱️",
                   "Start tiny and scale or commit big upfront? 👇",
                   "'Write one line of the doc.' Two minutes. The point is showing up daily, not the size of the rep."),
        "mistake": ("Going all-in day one is why you quit by day four ⚠️",
                    "Does an ambitious start guarantee an early quit? 👇",
                    "You committed to an hour a day. Missed day three, felt like a failure, stopped. Two minutes would've survived."),
        "scenario": ("He committed to 'open the editor.' That was enough 🎯",
                     "Tiny non-negotiable habit or ambitious flexible one? 👇",
                     "The rule was just 'open it.' He almost always did more — but the streak never broke because the bar was tiny."),
    },
    "Friction": {
        "tactic": ("Delete the steps between you and the important work 🧹",
                   "Reduce friction or just try harder to focus? 👇",
                   "Every extra click before deep work is an exit. Pre-open the file, kill the logins, clear the path."),
        "mistake": ("Each tiny barrier is a silent reason you didn't do it ⚠️",
                    "Do small frictions actually decide your whole output? 👇",
                    "It wasn't laziness. It was the VPN, the login, the search every single time. Friction quietly won."),
        "scenario": ("She bookmarked the one doc. Daily work resumed 🎯",
                     "Is most procrastination just unremoved friction? 👇",
                     "The work restarted the day she removed the four clicks it took to even reach it."),
    },
    "Commitment": {
        "tactic": ("Add friction to the bad habit, not just the good one 🚧",
                   "Block the distraction by design or by willpower? 👇",
                   "Log out of the time-sink. Make the bad default a hassle and you'll stop choosing it without trying."),
        "mistake": ("Relying on 'I'll resist it' is why the distraction wins ⚠️",
                    "Is resisting an easy distraction realistic at hour seven? 👇",
                    "You kept the tab one click away and trusted your willpower. The tab won by Tuesday."),
        "scenario": ("He used a blocker during deep-work blocks. Output jumped 🎯",
                     "Hard-block distractions or trust self-control? 👇",
                     "Two focus hours, site blocker on, phone in a drawer. The work he'd dodged for weeks shipped in three days."),
    },
    "4th Law": {
        "tactic": ("Make progress visible so the work rewards itself 🟩",
                   "Do you need to see progress or is the goal enough? 👇",
                   "A visible streak or a moving bar makes the habit satisfying enough to repeat without forcing it."),
        "mistake": ("Invisible progress is why good habits feel pointless ⚠️",
                    "Does unseen progress kill motivation faster than failure? 👇",
                    "You were improving and couldn't feel it, so you quit. Make it visible or it won't survive."),
        "scenario": ("She tracked shipped wins on one visible list 🎯",
                     "Track wins visibly or just keep your head down? 👇",
                     "A running 'shipped' list on her wall. Seeing it grow was the thing that kept the habit alive — and fed her review."),
    },
    "Cardinal Rule": {
        "tactic": ("Give yourself an instant signal the rep counted ✅",
                   "Need an immediate payoff or can you delay gratification? 👇",
                   "Career rewards are slow. Add a tiny immediate marker after each rep so the brain repeats it."),
        "mistake": ("No immediate reward is why the good habit dies quietly ⚠️",
                    "Is 'it'll pay off eventually' enough to sustain a habit? 👇",
                    "The payoff was a year out. The brain needed something today. It got nothing, so it stopped."),
        "scenario": ("He checked a box after each deep-work block. It stuck 🎯",
                     "Is a trivial 'done' marker enough to sustain effort? 👇",
                     "One satisfying checkmark per session. Childish, and it's the reason the habit outlived motivation."),
    },
    "Tracking": {
        "tactic": ("Don't break the chain — the streak becomes the motivation 🔗",
                   "Does a visible streak actually keep you consistent? 👇",
                   "Mark every day you did the rep. Soon you protect the chain itself, not the outcome."),
        "mistake": ("Not tracking is why you can't tell progress from drift ⚠️",
                    "Is untracked effort basically invisible to your own brain? 👇",
                    "You felt like you were improving. No record, no proof, no momentum. The feeling faded; nothing held it up."),
        "scenario": ("She kept a 40-day streak. She wouldn't be the one to break it 🎯",
                     "Is streak pressure healthy motivation or fragile? 👇",
                     "By day 40 the habit ran itself — not for the goal, but because nobody breaks a 40-day chain on purpose."),
    },
    "Never Miss Twice": {
        "tactic": ("Missed once is human. Never miss twice 🔁",
                   "Is one skipped day fine or the first domino? 👇",
                   "The rule isn't 'never miss.' It's 'never miss two in a row.' That single rule saves every habit."),
        "mistake": ("'I already broke it this week' is the lie that ends habits ⚠️",
                    "Does one slip justify writing off the whole week? 👇",
                    "One miss became 'the week's blown,' became a month off. The miss didn't end it. The story did."),
        "scenario": ("He missed Monday, refused to miss Tuesday. Habit survived 🎯",
                     "After a slip: restart now or 'next Monday'? 👇",
                     "Skipped a day, felt the pull to quit, showed up the next day anyway. That one choice kept the streak's spirit alive."),
    },
    "Accountability": {
        "tactic": ("Make the commitment public so dropping it costs you 📣",
                   "Does telling people your goal help or just add pressure? 👇",
                   "Tell your manager the thing you'll ship by Friday. Public stakes finish what private intentions don't."),
        "mistake": ("Private goals with zero stakes are the easiest to abandon ⚠️",
                    "Are silent personal goals just permission to quit? 👇",
                    "No one knew, so no one noticed when you stopped — including, eventually, you."),
        "scenario": ("She told the team her deadline. It shipped on time 🎯",
                     "Commit publicly to a date or keep it flexible? 👇",
                     "She announced 'demo Friday' in standup. The public date did what three private to-do lists hadn't."),
    },
    "Goldilocks": {
        "tactic": ("Take the task just past your current level 🎯",
                   "Stretch slightly or stay where you're comfortable? 👇",
                   "Growth lives at the edge of your ability — hard enough to engage, not so hard you stall."),
        "mistake": ("Coasting on easy work is the most comfortable career death ⚠️",
                    "Is staying in your comfort zone safe or slowly fatal? 👇",
                    "You did what you were already good at for two years. You didn't fail. You just didn't grow, and it showed."),
        "scenario": ("He asked for the task one notch above him. He leveled up 🎯",
                     "Volunteer for the slightly-too-hard task or wait? 👇",
                     "He took the project he wasn't quite ready for. Sweated it, shipped it, and came out a level higher."),
    },
    "Reflection": {
        "tactic": ("Run a 15-minute weekly review of your own work ♻️",
                   "Is a weekly self-review worth the time or overhead? 👇",
                   "Friday: what worked, what didn't, what changes Monday. The unreviewed career repeats its mistakes."),
        "mistake": ("Never reviewing is why you make the same mistake quarterly ⚠️",
                    "Do you learn from your work or just survive it? 👇",
                    "Same misstep, three quarters running, because there was never a moment to notice the pattern."),
        "scenario": ("She did Friday reviews. Her mistakes stopped repeating 🎯",
                     "Weekly reflection ritual or just keep moving? 👇",
                     "Fifteen minutes every Friday. Within two months the recurring errors were gone and her judgment visibly sharpened."),
    },
    "Mindfulness": {
        "tactic": ("Stay alert to drift — autopilot hides slow decline 👁️",
                   "Does coasting on autopilot quietly cost you years? 👇",
                   "Even good habits decay when you stop paying attention. Periodically check you're still aimed right."),
        "mistake": ("Going on career autopilot is how five years vanish ⚠️",
                    "Is 'just keep doing what works' wisdom or a trap? 👇",
                    "You ran the same play for years without checking if it still worked. It stopped working a while ago."),
        "scenario": ("He caught his own coasting before the review did 🎯",
                     "Self-correct early or wait for feedback to force it? 👇",
                     "A quarterly honest check flagged the drift. He adjusted before it became someone else's note about him."),
    },
    "Synthesis": {
        "tactic": ("Small consistent reps stack into an undeniable case 🧱",
                   "Is a career won by moments or accumulated habits? 👇",
                   "No single rep matters. The promotion case is the year of them, compounded and visible."),
        "mistake": ("Chasing the one big moment ignores what actually compounds ⚠️",
                    "Big swing or steady stack — which builds a career? 👇",
                    "You waited for the defining project. The person with a year of small visible wins got promoted first."),
        "scenario": ("Year-end review: her case was 50 small documented wins 🎯",
                     "Build a promotion case from one win or fifty? 👇",
                     "He had one big thing. She had fifty logged small ones. The committee found her case impossible to argue with."),
    },
    "Closing": {
        "tactic": ("You are what you repeatedly do at work — design it 🔁",
                   "Is your reputation your talent or your daily defaults? 👇",
                   "Nobody sees your potential. They see your patterns. Build the patterns you want to be known for."),
        "mistake": ("Waiting to 'become' someone instead of acting like them ⚠️",
                    "Do you become senior by feeling ready or by acting it? 👇",
                    "You waited to feel like a leader before behaving like one. The behavior was always the only path."),
        "scenario": ("A year of deliberate small habits rewrote his title 🎯",
                     "Can boring daily habits actually change your career? 👇",
                     "No single dramatic move. Just a year of designed daily defaults. The new role was the receipt."),
    },

    # ──────────────────────────── 12 RULES FOR LIFE ────────────────────────────
    "12 Rules for Life": {
        "tactic": ("Order beats chaos — run your work life on rules 🧭",
                   "Do personal operating rules help at work or overthink it? 👇",
                   "A few hard personal rules — when you speak, what you commit to — make the chaotic office navigable."),
        "mistake": ("Winging office politics with no principles is why it eats you ⚠️",
                    "Improvise every workplace situation or have set rules? 👇",
                    "With no rules, every hard moment was decided by your worst impulse in the moment. It showed."),
        "scenario": ("She had three non-negotiable work rules. They held 🎯",
                     "Are personal work rules a crutch or an edge? 👇",
                     "Three rules she never broke under pressure. In the messy quarters, they were the reason she stayed trusted."),
    },
    "Rule 1": {
        "tactic": ("Posture and presence change how seriously you're taken 🦅",
                   "Does physical presence really affect workplace authority? 👇",
                   "Shoulders back, steady voice, take the space. People assign competence to presence before they hear your point."),
        "mistake": ("Shrinking in the room signals 'don't take me seriously' ⚠️",
                    "Is the quiet hunched contributor overlooked unfairly or predictably? 👇",
                    "Your work was strong and your body said 'sorry to exist.' The room read the body first."),
        "scenario": ("He changed how he entered meetings. He got interrupted less 🎯",
                     "Does standing tall in meetings change outcomes or not? 👇",
                     "Same arguments, new presence — slower, grounded, unhurried. People stopped talking over him within a week."),
    },
    "Rule 2": {
        "tactic": ("Manage your career like you'd manage someone you're responsible for 💼",
                   "Would you let a report self-neglect like you do? 👇",
                   "You'd never let a junior skip growth, rest, or advocacy. Give yourself the same management."),
        "mistake": ("Neglecting your own development while serving everyone else's ⚠️",
                    "Is being endlessly 'helpful' generous or self-erasing? 👇",
                    "You invested in everyone's projects and none of your own. Helpful, invisible, and overdue for a hard look."),
        "scenario": ("She booked her own growth like a report's 1:1 🎯",
                     "Schedule your own development or hope it happens? 👇",
                     "She gave herself the standing dev-time she'd give any report. In a year she was the one giving the 1:1s."),
    },
    "Rule 3": {
        "tactic": ("Build your circle from people who want you to win 🤝",
                   "Do your closest work allies actually root for you? 👇",
                   "Audit who you spend office energy on. Drift toward the ones who push you up, not the ones who anchor you."),
        "mistake": ("Loyalty to people who keep you small is a slow career tax ⚠️",
                    "Stay loyal to a draining work clique or move on? 👇",
                    "You stayed close to the group that mocked ambition. You absorbed their ceiling and called it loyalty."),
        "scenario": ("He changed who he ate lunch with. His trajectory changed 🎯",
                     "Do your lunch people lift you or level you down? 👇",
                     "New table: people building things. Old table: people complaining. Six months later only one group had moved."),
    },
    "Rule 4": {
        "tactic": ("Benchmark against yesterday-you, not the office star 📈",
                   "Compare to top performers or to your past self? 👇",
                   "Measuring against the team's best burns you out. Measuring against last-quarter-you compounds you forward."),
        "mistake": ("Comparing to the top performer is a motivation killer ⚠️",
                    "Does comparing up drive you or quietly demoralize you? 👇",
                    "You measured every week against the team's star and felt like nothing. The metric, not the work, was the problem."),
        "scenario": ("She tracked her own delta. Confidence and output rose 🎯",
                     "Is self-comparison healthier fuel than peer-comparison? 👇",
                     "She stopped watching the top performer and started beating last month's self. Both her mood and her reviews climbed."),
    },
    "Rule 5": {
        "tactic": ("Don't tolerate behavior that erodes your respect for a report 🧱",
                   "Address a likable report's bad habit early or let it slide? 👇",
                   "Small unaddressed behaviors curdle into resentment you can't hide. Correct it early, kindly, before you dislike them."),
        "mistake": ("Avoiding the hard feedback is how good people quietly fail ⚠️",
                    "Is withholding tough feedback kindness or cowardice? 👇",
                    "You spared them the hard conversation for a year. The PIP was the first time they ever heard it. That's on you."),
        "scenario": ("He gave the uncomfortable feedback at week two, not month ten 🎯",
                     "Early blunt feedback or wait for the 'right moment'? 👇",
                     "Awkward two-minute conversation early. It saved the report, the project, and a relationship a late PIP would've ended."),
    },
    "Rule 6": {
        "tactic": ("Fix your own work before you criticize the org 🧹",
                   "Earn the right to critique by delivering first — fair? 👇",
                   "Criticism from someone whose own house is in order lands. From someone whose isn't, it's just noise."),
        "mistake": ("Loudly diagnosing the company while your own work slips ⚠️",
                    "Is the office critic insightful or just deflecting? 👇",
                    "You had strong opinions on everything broken and a backlog of your own. People noticed which came first."),
        "scenario": ("She nailed her delivery, then her critique got heard 🎯",
                     "Critique up only after your own results are clean? 👇",
                     "Once her own work was undeniable, the same feedback she'd given for months suddenly carried weight."),
    },
    "Rule 7": {
        "tactic": ("Choose the meaningful project over the easy visible one 🎯",
                   "Take the quick-win optics or the hard meaningful work? 👇",
                   "Expedient wins fade by next quarter. The hard problem you actually solved becomes your reputation."),
        "mistake": ("Chasing only quick wins builds a thin, brittle reputation ⚠️",
                    "Is a string of easy wins a career or a house of cards? 👇",
                    "You optimized for fast optics for two years. When the hard problem came, no one trusted you with it."),
        "scenario": ("He took the unglamorous hard problem. It defined him 🎯",
                     "Be known for many quick wins or one hard solve? 👇",
                     "Everyone chased the visible quick wins. He took the ugly foundational problem. Now he's the person they call."),
    },
    "Rule 8": {
        "tactic": ("Don't lie at work — especially the small convenient ones 🎯",
                   "Is a small status-update white lie harmless or corrosive? 👇",
                   "The 'almost done' that wasn't, the 'no issues' that had them. Small lies compound into a trust deficit you can't repay."),
        "mistake": ("Optimistic status lies are the fastest way to lose trust ⚠️",
                    "Does 'on track' when it isn't ever end well? 👇",
                    "You said green to avoid the hard conversation. The red surfaced anyway, plus now you're the one who hid it."),
        "scenario": ("She flagged the slip early and honestly. Trust went up 🎯",
                     "Report a slip the day it happens or hope to recover? 👇",
                     "She said 'this is at risk and here's why' on day one. Uncomfortable, and the reason leadership now believes her greens."),
    },
    "Rule 9": {
        "tactic": ("Assume the person you're dismissing knows something you don't 👂",
                   "Listen to learn or wait for your turn to talk? 👇",
                   "Walk into the disagreement assuming they see something you can't yet. You'll catch the thing that saves the project."),
        "mistake": ("Dismissing 'obviously wrong' colleagues is how you miss the catch ⚠️",
                    "Is the person you tune out usually wrong — or inconvenient? 👇",
                    "You'd already decided they were wrong, so you didn't hear the risk they were flagging. It shipped. It broke."),
        "scenario": ("He actually listened to the junior's objection. It saved the launch 🎯",
                     "Hear out the junior's pushback or trust your read? 👇",
                     "The newest person raised a quiet concern. He almost talked past it. He didn't, and it was the bug that mattered."),
    },
    "Rule 10": {
        "tactic": ("Be precise — vague asks at work create vague disasters 🎯",
                   "Is most workplace conflict really just imprecise language? 👇",
                   "'Soon,' 'mostly done,' 'handle it.' Name the exact deliverable, owner, and date or own the mess that follows."),
        "mistake": ("Vague commitments are the root of most missed deadlines ⚠️",
                    "Is 'I'll get it to you soon' a commitment or an escape? 👇",
                    "Nobody lied. 'Soon' just meant four different things to four people, and the deadline absorbed all four."),
        "scenario": ("She forced precise asks. The team stopped missing deadlines 🎯",
                     "Pin exact dates/owners or keep it flexible and friendly? 👇",
                     "Every action item got a name and a date or it didn't leave the meeting. Slips dropped to near zero in a month."),
    },
    "Rule 11": {
        "tactic": ("Let competent people take risks — don't smother the bold ones 🛹",
                   "Should you shield a high performer from every risk? 👇",
                   "Over-protecting your best people from stretch and failure is how you make them mediocre and resentful."),
        "mistake": ("Micromanaging your strongest performer is how you lose them ⚠️",
                    "Does heavy oversight protect quality or kill your best people? 👇",
                    "You hovered to keep standards high. Your strongest hire felt distrusted, stopped taking initiative, then left."),
        "scenario": ("He stopped hovering. His best engineer leveled up fast 🎯",
                     "Give a top performer rope or keep a tight leash? 👇",
                     "He backed off the daily check-ins. Given room to risk and recover, she shipped the thing he couldn't have."),
    },
    "Rule 12": {
        "tactic": ("In a brutal quarter, take the small recovery wins 🐈",
                   "Is acknowledging small wins soft or survival? 👇",
                   "When everything's on fire, the people who notice and bank the tiny good moments are the ones still standing at Q4."),
        "mistake": ("Grinding through chaos with zero recovery is how you burn out ⚠️",
                    "Is 'push through, no breaks' resilience or a countdown? 👇",
                    "You powered through the death-march quarter refusing every small pause. You hit the deadline and then hit a wall."),
        "scenario": ("She protected small recovery moments mid-crisis. She lasted 🎯",
                     "In a crunch, do micro-breaks help or just slow you? 👇",
                     "Everyone sprinted to empty. She took the small daily resets. At the end, she was the one still able to think."),
    },
}


import re

SUB = "SUBSCRIBE FOR THE REST"


def book_for(item: dict, default_book: str) -> str:
    return item.get("book") or default_book


def parent_label(item: dict) -> str:
    """Stable series anchor — the parent law/rule/principle title."""
    return item["title"]


def series_label(book: str, title: str, book_pos: int, book_total: int) -> str:
    """Book-aware, STABLE-PARENT-number series label for the loop overlay.

    Uses the parent law/rule number (identical across that parent's
    TACTIC/MISTAKE/SCENARIO trio) — never the flat item index — so the
    "incomplete series -> subscribe" FOMO stays intact and we never print
    'Law 137 of 48'. Intros are number-free.
    """
    bl = book.lower()
    if "48 laws" in bl:
        m = re.fullmatch(r"Law (\d+)", title)
        return f"LAW {m.group(1)}/48  ·  {SUB}" if m else f"THE 48 LAWS  ·  {SUB}"
    if "12 rules" in bl:
        m = re.fullmatch(r"Rule (\d+)", title)
        return f"RULE {m.group(1)}/12  ·  {SUB}" if m else f"12 RULES  ·  {SUB}"
    if "atomic habits" in bl:
        # Themed concepts, not numbered "habits" — position/total, never "Habit N".
        return f"ATOMIC HABITS  ·  {book_pos}/{book_total}  ·  {SUB}"
    return f"{book.upper()}  ·  {SUB}"


def main() -> int:
    src = json.loads(SRC.read_text(encoding="utf-8"))
    default_book = src["book"]
    default_author = src["author"]

    missing = [d["title"] for d in src["days"] if d["title"] not in V]
    if missing:
        print(f"ERROR: {len(missing)} parents have no authored variants:")
        for m in missing:
            print(f"  - {m}")
        return 1

    # Per-book parent ordering (1-based) + totals, for the Atomic-Habits
    # position/total label (its parents are themed, not numbered).
    book_seq: dict[str, int] = {}
    book_total: dict[str, int] = {}
    for d in src["days"]:
        b = book_for(d, default_book)
        book_total[b] = book_total.get(b, 0) + 1

    items: list[dict] = []
    order = 0
    for d in src["days"]:
        title = d["title"]
        book = book_for(d, default_book)
        book_seq[book] = book_seq.get(book, 0) + 1
        label = series_label(book, title, book_seq[book], book_total[book])
        for vtype in ("tactic", "mistake", "scenario"):
            tease, comment_q, body = V[title][vtype]
            order += 1
            items.append({
                "item": order,
                "parent_law": parent_label(d),
                "book": book,
                "title": title,
                "headline": d["headline"],
                "author": d.get("author", default_author),
                "variant_type": vtype.upper(),
                "series_label": label,
                "tease": tease,
                "comment_q": comment_q,
                "body": body,
            })

    out = {
        "book": default_book,
        "author": default_author,
        "positioning": "Corporate survival tactics, decoded from the 3 books that "
                       "actually teach workplace power.",
        "items": items,
    }
    SRC.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Wrote {len(items)} variant items from {len(src['days'])} parents -> {SRC}")
    by_book: dict[str, int] = {}
    for it in items:
        by_book[it["book"]] = by_book.get(it["book"], 0) + 1
    for b, n in by_book.items():
        print(f"  {b}: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
